local wk = require("which-key")

wk.add({
  -- Main screen
  { "<leader>A", ":Alpha<CR>", desc = "Main dashboard", mode = "n", icon = "󰨝" },
  -- Neotree
  { "<leader><Tab>", ":Neotree toggle<CR>", desc = "Neotree", mode = "n", icon = "" },
  -- Lazy
  { "<leader>L", ":Lazy<CR>", desc = "Lazy plugins manager", mode = "n", icon = "󱧘" },
  -- Telescope
  { "<leader>f", group = "Telescope" },
  { "<leader><leader>", ":Telescope find_files<CR>", desc = "Find file", mode = "n" },
  { "<leader>fh", ":Telescope builtin<CR>", desc = "Telescope show pickers" },
  { "<leader>fD", ":Telescope diagnostics<CR>", desc = "LSP diagnostics", mode = "n" },
  { "<leader>fc", ":Telescope commands<CR>", desc = "Find command", mode = "n" },
  { "<leader>fw", ":lua require('telescope.builtin').grep_string()<CR>", desc = "Find under cursor", mode = "n" },
  { "<leader>fF", ":Telescope current_buffer_fuzzy_find<CR>", desc = "Find within buffer", mode = "n" },
  { "<leader>fb", ":Telescope buffers<CR>", desc = "Buffers", mode = "n" },
  { "<leader>fs", ":Telescope lsp_document_symbols<CR>", desc = "LSP symbols" },
  { "<leader>ff", ":lua require('telescope').extensions.recent_files.pick()<CR>", desc = "Recent files", mode = "n" },
  -- Neovim
  { "<leader>n", group = "Neovim", icon = "" },
  { "<leader>nh", ":Telescope help_tags<CR>", desc = "Find help", mode = "n" },
  { "<leader>nt", ":Telescope colorscheme<CR>", desc = "Themes", mode = "n" },
  { "<leader>nk", ":map<CR>", desc = "Show keys", mode = "n" },
  -- Mason
  { "<leader>M", ":Mason<CR>", desc = "Mason", mode = "n", icon = "" },
  -- LazyGit
  { "<leader>G", ":LazyGit<CR>", desc = "Lazy Git" },
  -- Terminal
  { "<leader>o", group = "Terminal" },
  { "<leader>ot", ":terminal<cr>", desc = "Open terminal in a new buffer", mode = "n" },
  { "<leader>of", ":FloatermToggle<cr>", desc = "Toggle floating terminal" },
  -- LSP
  { "gd", ":Telescope lsp_definitions<CR>", desc = "LSP goto definition" },
  { "gr", ":Telescope lsp_references<CR>", desc = "LSP references" },
  { "gO", ":Telescope lsp_outgoing_calls <CR>", desc = "LSP outgoing calls" },
  { "gI", ":Telescope lsp_incoming_calls<CR>", desc = "LSP incoming calls" },
  { "go", ":ClangdSwitchSourceHeader<CR>", desc = "Clangd switch between source and header" },
  { "<F2>", vim.lsp.buf.rename, desc = "LSP rename" },
  { "ca", vim.lsp.buf.code_action, desc = "LSP code actions" },
  { "<leader>fm", vim.lsp.buf.format, desc = "LSP format file" },
  -- DAP
  { "<leader>d", group = "Debug", icon = "󰯆" },
  { "<leader>d<Tab>", ":lua require('dapui').toggle()<CR>", desc = "Toggle UI", icon = "" },
  { "<leader>db", ":lua require('dap').toggle_breakpoint()<CR>", desc = "Toggle breakpoint", icon = "" },
  { "<leader>dC", ":lua require('dap').clear_breakpoints()<CR>", desc = "Clear breakpoint", icon = "" },
  { "<leader>d<Enter>", ":lua require('dap').continue()<CR>", desc = "Run or continue", icon = "" },
  { "<leader>dD", ":lua require('dap').terminate()<CR>", desc = "Terminate session", icon = "" },
  { "<leader>dc", ":lua require('dap').continue()<CR>", desc = "Continue", icon = "" },
  { "<leader>ds", ":lua require('dap').step_into()<CR>", desc = "Step into", icon = "" },
  { "<leader>dn", ":lua require('dap').step_over()<CR>", desc = "Step over", icon = "" },
  { "<leader>dO", ":lua require('dap').step_out()<CR>", desc = "Step out", icon = "" },
  -- Windows
  { "<leader>w", group = "Windows", icon = "" },
  { "<leader>wh", ":split<CR>", desc = "Horizontal split", mode = "n" },
  { "<leader>wv", ":vsplit<CR>", desc = "Vertical split", mode = "n" },
  -- Essentials
  { "<ESC>", [[<C-\><C-n>:close<CR>]], mode = "t" }, -- Exit from lazygit with Esc
  { "<leader>x", ":.lua<CR>", desc = "Execute current lua line", mode = "n", icon = "" },
  { "<leader>x", ":lua<CR>", desc = "Execute current lua selection", mode = "v", icon = "" },
  { "<leader>r", ":source %<CR>", desc = "Reload current lua file", mode = "n", icon = "" },
  { "<C-s>", ":write<CR>", desc = "Save current buffer", mode = "n" },
  { "<C-s>", "<C-\\><C-o>:w<CR>", desc = "Save current buffer", mode = "i" },
  { "<C-S-s>", ":wq<CR>", desc = "Exit", mode = "n" },
  { "<C-k>", ":wincmd k<CR>", mode = "n" },
  { "<C-j>", ":wincmd j<CR>", mode = "n" },
  { "<C-h>", ":wincmd h<CR>", mode = "n" },
  { "<C-l>", ":wincmd l<CR>", mode = "n" },
  { "]d", ":lua vim.diagnostic.goto_next()<CR>", desc = "Next LSP diagnostics", mode = "n" },
  { "[d", ":lua vim.diagnostic.goto_prev()<CR>", desc = "Previous LSP diagnostics", mode = "n" },
  { "<C-h>", "<Left>", mode = "i" },
  { "<C-l>", "<Right>", mode = "i" },
  { "<C-k>", "<Up>", mode = "i" },
  { "<C-j>", "<Down>", mode = "i" },
  { "<C-w>", "<C-O>w", mode = "i" },
  { "<C-b>", "<C-O>b", mode = "i" },
  { "\"", "\"\"<C-G>U<Left>", mode = "i" },
  { "'", "''<C-G>U<Left>", mode = "i" },
  { "<leader>/", ":nohlsearch<CR>", mode = "n", hidden = true },
  { "<leader>nc", ":checkhealth<CR>", desc = "Check health", mode = "n" },
  { ";", ":", desc = "CMD enter command mode", mode = "n" },
  -- Move lines up/down
  { "<A-j>", ":m .+1<CR>==", desc = "Move line down", mode = "n" },
  { "<A-k>", ":m .-2<CR>==", desc = "Move line up", mode = "n" },
  { "<A-j>", ":m '>+1<CR>gv=gv", desc = "Move selection down", mode = "v" },
  { "<A-k>", ":m '<-2<CR>gv=gv", desc = "Move selection up", mode = "v" },
  -- Indenting in visual mode
  { "<", "<gv", desc = "Indent left" },
  { ">", ">gv", desc = "Indent right" },
  -- Buffer navigation
  { "<leader>b", group = "Buffers" },
  { "<Tab>", ":BufferNext<cr>", desc = "Buffer next", mode = "n" },
  { "<leader>bn", ":BufferNext<cr>", desc = "Buffer next", mode = "n" },
  { "<S-Tab>", ":BufferPrevious<cr>", desc = "Buffer previous", mode = "n" },
  { "<leader>bp", ":BufferPrevious<cr>", desc = "Buffer previous", mode = "n" },
  { "<leader>bb", ":tabnew<cr>", desc = "New tab with a buffer", mode = "n" },
  { "<leader>bd", ":BufferClose<cr>", desc = "Buffer close", mode = "n" },
  { "<leader>bq", ":BufferClose<cr>", desc = "Buffer close", mode = "n" },
  { "<leader>bk", ":BufferClose<cr>", desc = "Buffer close", mode = "n" },
  { "<leader>bP", ":BufferMovePrevious<cr>", desc = "Buffer move previous", mode = "n" },
  { "<leader>bN", ":BufferMoveNext<cr>", desc = "Buffer move next", mode = "n" },
  { "<leader>b1", ":BufferGoto 1<cr>", desc = "Buffer goto 1", mode = "n" },
  { "<leader>b2", ":BufferGoto 2<cr>", desc = "Buffer goto 2", mode = "n" },
  { "<leader>b3", ":BufferGoto 3<cr>", desc = "Buffer goto 3", mode = "n" },
  { "<leader>b4", ":BufferGoto 4<cr>", desc = "Buffer goto 4", mode = "n" },
  { "<leader>b5", ":BufferGoto 5<cr>", desc = "Buffer goto 5", mode = "n" },
  { "<leader>b6", ":BufferGoto 6<cr>", desc = "Buffer goto 6", mode = "n" },
  { "<leader>b7", ":BufferGoto 7<cr>", desc = "Buffer goto 7", mode = "n" },
  { "<leader>b8", ":BufferGoto 8<cr>", desc = "Buffer goto 8", mode = "n" },
  { "<leader>b9", ":BufferGoto 9<cr>", desc = "Buffer goto 9", mode = "n" },
  -- Flash search within the buffer
  { "<C-f>", function() require("flash").jump() end, desc = "Flash search", mode = "n" },
  -- Touble keymaps
  { "<leader>D", group = "Diagnostics", icon = "" },
  { "<leader>Dx", ":Trouble diagnostics toggle<cr>", desc = "Diagnostics (Trouble)", },
  { "<leader>Db", ":Trouble diagnostics toggle filter.buf=0<cr>", desc = "Buffer Diagnostics (Trouble)", },
  { "<leader>Ds", ":Trouble symbols toggle focus=false<cr>", desc = "Symbols (Trouble)", },
  { "<leader>Dl", ":Trouble lsp toggle focus=false win.position=right<cr>", desc = "LSP Definitions / references / ... (Trouble)", },
  { "<leader>DL", ":Trouble loclist toggle<cr>", desc = "Location List (Trouble)", },
  { "<leader>DQ", ":Trouble qflist toggle<cr>", desc = "Quickfix List (Trouble)", },
})
